# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'mertsenel/devopschallengesalesapi'


steps:

- task: Docker@2
  displayName: Docker Build & Unit Tests
  inputs:
    containerRegistry: 'MertSenel GitHub Container Registry'
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: 'src/DevOpsChallenge.SalesApi/Dockerfile'
    buildContext: '$(Build.Repository.LocalPath)'

- pwsh: |
    $id=docker images --filter "label=test=true" -q | Select-Object -First 1
    docker create --name testcontainer $id
    docker cp testcontainer:/testresults ./testresults
    docker rm testcontainer
  displayName: 'Copy test results'
  condition: succeededOrFailed()
   
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    searchFolder: '$(System.DefaultWorkingDirectory)/testresults'
  displayName: 'Publish test results'
  condition: succeededOrFailed()

- task: Docker@2
  displayName: Docker Push Container Image
  inputs:
    containerRegistry: 'MertSenel GitHub Container Registry'
    repository: $(imageName)
    command: 'push'